# Generated by Django 5.2.3 on 2025-07-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payments/qrcodes/'),
        ),
    ]
