# Generated by Django 5.2.3 on 2025-07-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.CharField(blank=True, help_text='Adresse de livraison, si applicable', max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='comment',
            field=models.TextField(blank=True, help_text='Informations ou instructions complémentaires'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='method',
            field=models.CharField(choices=[('home', 'Livraison à domicile'), ('boutique', 'Retrait en boutique'), ('seller', 'Livraison par le vendeur'), ('personal', 'Livreur personnel')], default='home', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_code',
            field=models.CharField(blank=True, help_text='Code secret à remettre lors de la livraison (pour QR code)', max_length=12),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('assigned', 'Assignée'), ('in_transit', 'En livraison'), ('delivered', 'Livrée'), ('failed', 'Échec'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
