# Generated by Django 5.2.3 on 2025-07-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_address_delivery_comment_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Commentaire du client sur le livreur'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='note',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Note du livreur (1 à 5)', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='qr_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
