# Generated by Django 5.2.3 on 2025-07-02 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_wishlist_unique_together_wishlist_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
